[tool.poetry]
name = "stas-monitering"
version = "0.1.0"
description = ""
authors = ["kenya-sk"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
hydra-core = "^1.0.6"
matplotlib = "^3.4.1"
opencv-python = "^4.5.1"
pandas = "^1.2.4"
seaborn = "^0.11.1"
tqdm = "^4.60.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
