version: '3.3'
services:
  detection-gpu:
    platform: linux/x86_64
    build:
      context: ./individual-detection
      dockerfile: Dockerfile
    runtime: nvidia
    image: deep-detection-gpu
    container_name: deep-detection-gpu
    volumes:
      - type: bind
        source: /data/detection
        target: /workspace/data
    tty: true

  tracker:
    build:
      context: ./individual-tracking
      dockerfile: Dockerfile
    image: deep-tracker
    container_name: deep-tracker
    volumes:
      - type: bind
        source: /data/tracking
        target: /workspace/data
    tty: true

  monitoring:
    build:
      context: ./stats-monitoring
      dockerfile: Dockerfile
    image: deep-monitoring
    container_name: deep-monitoring
    volumes:
      - type: bind
        source: /data/monitoring
        target: /workspace/data
    tty: true
  # annotator:
  #   build:
  #     context: ./density-annotator
  #     dockerfile: Dockerfile
  #   image: deep-annotator
  #   container_name: deep-annotator
  #   volumes:
  #     - type: bind
  #       source: /data
  #       target: /workspace/data
  #   tty: true
