# Each unit is a pixel.

animation:
  format: ffmpeg
  frame_number: 9000
  interval: 33  # milli second
  display_dot: False
  display_density: False

# The initial value of figure is the same as frame,
# but it is converted to the required value in the function.
graph:
  x_axis_height: 240
  y_axis_height: 240
  stats_graph_num: 3
  margin: 20
  font_size: 18

histogram:
  x_bin_granularity: 50
  y_bin_granularity: 50

statistics:
  mean_max: 120
  acceleration_max: 150
  count_max: 70

# relative path from data directory
path:
  frame_directory: frame/tracking
  coordinate_directory: coordinate/tracking/current
  past_coordinate_directory: coordinate/tracking/past
  mean_speed_path: stats/mean/tracking/current/mean.csv
  past_mean_speed_path: stats/mean/tracking/past/mean.csv
  individual_count_path: stats/count/tracking/current/count.csv
  past_individual_count_path: stats/count/tracking/past/count.csv
  acceleration_count_path: stats/acceleration/tracking/current/acceleration.csv
  past_acceleration_count_path: stats/acceleration/tracking/past/acceleration.csv
  save_movie_path: movie/tracking_2018.mp4
