# Each unit is a pixel.

animation:
  format: ffmpeg
  frame_number: 9000
  interval: 33  # milli second
  density_interval: 30  # frame num
  display_dot: False
  display_density: False

histogram:
  x_bin_granularity: 50
  y_bin_granularity: 50

statistics:
  mean_max: 210
  acceleration_max: 70

# relative path from data directory
path:
  frame_directory: frame
  coordinate_directory: coordinate/current
  past_coordinate_directory: coordinate/past
  mean_speed_path: stats/current/mean.csv
  past_mean_speed_path: stats/past/mean.csv
  acceleration_count_path: stats/current/acceleration.csv
  past_acceleration_count_path: stats/past/acceleration.csv
  save_movie_path: movie/monitoring.mp4
