image_directory: "/data/image/raw/all"
density_directory: "/data/dens/all"
mask_path: "/data/image/mask.png"
pretrained_model_path: ""
tensorboard_directory: "/data/tensorboard"
save_trained_model_directory: "/data/tensor_model"
# ID of using GPU: 0-max number of available GPUs
use_gpu_device: "0,1,2"
# using each GPU memory rate: 0.0-1.0
use_memory_rate: 0.9
# raw image information
image_height: 1080
image_width: 1920
image_channel: 3
# Image analysis area
analysis_image_height_min: 0
analysis_image_height_max: 720
analysis_image_width_min: 0
analysis_image_width_max: 1920
# test dataset size: 0.0-1.0
test_size: 0.2
# square local image size: > 0
local_image_size: 72
# batch size of training: > 0
batch_size: 512
# maximum number of epoch: > 0
n_epochs: 30
# minimum learning epoch (not apply early stopping): > 0
min_epochs: 5
# number of epochs for early stopping
early_stopping_epochs: 2
# probability of horaizontal flip. (apply only training data): 0.0-1.0
flip_prob: 0.5
# data below this value is target to under-sampling
under_sampling_thresh: 0.2
# dropout rate for each layer
dropout_rate: 0.5