sigma_pow: 25
mouse_event_interval: 1

# relative path from data directory
path:
  input_file_path: "demo/inputs"
  save_raw_image_dir: "demo/outputs/raw"
  save_annotated_dir: "demo/outputs/annotated"
