sampling_type: "random"
sample_rate: 9000

# relative path from data directory
path:
  input_video_list:
    - "video/demo_video_1.mp4"
    - "video/demo_video_2.mp4"
  save_frame_dirc: "sample_frame/"