# relative path from data directory
target_date: ""  # if extract only target date
trained_model_directory: "models/density_model/"
image_directory: "image/raw/all"
video_directory: "video"
output_directory: "predicted"
mask_path: "image/mask.png"

# select prediction data type (image or video)
predict_data_type: "image"
# interval at which local images are created and predictions are made
index_extract_type: "intersect"
skip_pixel_interval: 10
# Start and end time of video data (in 1-hour units)
start_hour: 9
end_hour: 17

# skip interval of frame at prediction [Need Rename]
predict_interval: 30
# batch size for each epoch
predict_batch_size: 5120
# save predicted density map (True or False)
is_saved_map: False
# band width of Mean-Shift Clustering
band_width: 10
# threshold to be subjected to clustering
cluster_thresh: 1.1