# relative path from data directory
image_directory: "image/raw/all"
density_directory: "dens/all"
mask_path: "image/mask.png"
pretrained_model_path: ""
save_dataset_path_directory: "datasets"
tensorboard_directory: "tensorboard"
save_trained_model_directory: "models"
# define logic for splitting the data set
dataset_split_type: "random"
train_date_list: 
  - "20170416"
  - "20170417"
  - "20170418"
  - "20170420"
  - "20170421"
  - "20170422"
  - "20181028"
  - "20181029"
  - "20181030"
  - "20181031"
valid_date_list: 
  - "20181101"
test_date_list: 
  - "20181102"
  - "20181103"

test_size: 0.2
# batch size of training: > 0
batch_size: 512
# maximum number of epoch: > 0
n_epochs: 30
# minimum learning epoch (not apply early stopping): > 0
min_epochs: 5
# number of epochs for early stopping
early_stopping_epochs: 2
# probability of horaizontal flip. (apply only training data): 0.0-1.0
flip_prob: 0.5
# data below this value is target to under-sampling
under_sampling_thresh: 0.2
# dropout rate  for each layer at training process
# 0.0: not apply dropout, 1.0: drop full units
dropout_rate: 0.5
hard_negative_weight: 3.0