name: annotator-test
on:
  push:
    branches:
      - main
    paths:
      - 'density-annotator/**'
  pull_request:
    paths:
      - 'density-annotator/**'

jobs:
  pytest:
    name: pytest for density-annotator
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./density-annotator
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup Python 3.8 environment
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: Run PyTest
        run: poetry run pytest tests -v
