name: monitoring-test
on:
  push:
    branches:
      - main
    paths:
      - 'stats-monitoring/**'
  pull_request:
    paths:
      - 'stats-monitoring/**'

jobs:
  pytest:
    name: pytest for stats-monitoring
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stats-monitoring
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Bulid Docker image
        run: docker build -t monitoring:latest ./ --build-arg PLATFORM="dev"
      # - name: Run PyTest
      #   run: docker run monitoring:latest pytest tests -v
